BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: 'Test'
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Button 1'  # + increment (up)
            Button:
                text: 'Button 2'  # - increment (down)
    Button:
        text: 'Convert m to km'
    Label:
        text: '54.17'